// <auto-generated />
using GestaoMercado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoMercado.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20251005222126_CriacaoTableGestao")]
    partial class CriacaoTableGestao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GestaoMercado.GestaoDTO", b =>
                {
                    b.Property<decimal>("Gasto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Lucro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeGestor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumVendas")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.ToTable("Gestao");
                });

            modelBuilder.Entity("GestaoMercado.ProdutoDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
